#!/usr/bin/env bash
# Regenerate plugins/catalog/skills/browse-skills/SKILL.md from each plugin's
# metadata. Run before pushing — the freshness of the catalog comes from
# committing the regenerated file, not from runtime fetching.
#
# For each plugin under plugins/<name>/:
#   - read plugin.json (name, description)
#   - enumerate skills/<name>/SKILL.md
#   - extract description from each SKILL.md frontmatter
# Emit the catalog markdown.

set -eu

repo_root="$(cd "$(dirname "$0")/.." && pwd)"
catalog_path="$repo_root/plugins/catalog/skills/browse-skills/SKILL.md"

if ! command -v python3 >/dev/null 2>&1; then
  echo "error: python3 required" >&2
  exit 1
fi

python3 - "$repo_root" "$catalog_path" <<'PY'
import json, os, re, sys
from pathlib import Path
from datetime import datetime, timezone

repo_root = Path(sys.argv[1])
catalog_path = Path(sys.argv[2])
plugins_dir = repo_root / "plugins"

def extract_frontmatter_field(skill_md_path, field):
    """Pull a top-level field from YAML-ish frontmatter (--- ... ---)."""
    try:
        text = skill_md_path.read_text(encoding="utf-8")
    except Exception:
        return None
    m = re.match(r"^---\s*\n(.*?)\n---\s*\n", text, flags=re.DOTALL)
    if not m:
        return None
    fm = m.group(1)
    # Single-line: "description: foo"
    line_re = re.compile(rf"^{re.escape(field)}\s*:\s*(.+?)$", flags=re.MULTILINE)
    m2 = line_re.search(fm)
    if m2:
        v = m2.group(1).strip().strip('"').strip("'")
        return v
    return None

now = datetime.now(timezone.utc).strftime("%Y-%m-%d")

lines = [
    "---",
    "name: browse-skills",
    "description: Lists every skill available in the `unatt` marketplace, including ones not installed on this machine. Use when the user asks what skills exist, when you want to suggest installing a skill that would help with the current task, or when the user mentions a tool/library that might be covered by an uninstalled plugin.",
    "---",
    "",
    "# unatt marketplace — skill catalog",
    "",
    "Auto-generated by `scripts/regen-catalog.sh`. Don't edit by hand.",
    "",
    f"**Marketplace:** `unatt` (github.com/unattachedgray/claude-skills)  ",
    f"**Last regenerated:** {now}",
    "",
    "## Install a plugin from this catalog",
    "",
    "```",
    "/plugin install <plugin>@unatt",
    "```",
    "",
    "## Plugins and their skills",
    "",
]

if not plugins_dir.is_dir():
    print(f"warning: {plugins_dir} not found", file=sys.stderr)
    sys.exit(0)

for plugin_dir in sorted(plugins_dir.iterdir()):
    if not plugin_dir.is_dir():
        continue
    manifest = plugin_dir / ".claude-plugin" / "plugin.json"
    if not manifest.is_file():
        continue
    try:
        manifest_data = json.loads(manifest.read_text(encoding="utf-8"))
    except Exception:
        continue
    plugin_name = manifest_data.get("name", plugin_dir.name)
    plugin_desc = manifest_data.get("description", "").strip()

    lines.append(f"### `{plugin_name}`")
    lines.append("")
    if plugin_desc:
        lines.append(plugin_desc)
        lines.append("")

    skills_dir = plugin_dir / "skills"
    skill_rows = []
    if skills_dir.is_dir():
        for skill_dir in sorted(skills_dir.iterdir()):
            if not skill_dir.is_dir():
                continue
            skill_md = skill_dir / "SKILL.md"
            if not skill_md.is_file():
                continue
            skill_name = skill_dir.name
            desc = extract_frontmatter_field(skill_md, "description") or "(no description)"
            # Truncate very long descriptions for the table — full text is in the SKILL.md itself.
            if len(desc) > 240:
                desc = desc[:237] + "..."
            skill_rows.append((skill_name, desc))

    if skill_rows:
        lines.append("| Skill | Description |")
        lines.append("|---|---|")
        for name, desc in skill_rows:
            # Escape pipes inside description for markdown table safety.
            desc_safe = desc.replace("|", "\\|")
            lines.append(f"| `/{plugin_name}:{name}` | {desc_safe} |")
        lines.append("")
    else:
        lines.append("_No skills declared._")
        lines.append("")

lines.append("---")
lines.append("")
lines.append("**Note:** Plugins use commit-SHA versioning — every push to the repo refreshes this catalog on all machines at next session start.")
lines.append("")

catalog_path.write_text("\n".join(lines), encoding="utf-8")
print(f"regenerated: {catalog_path}")
PY
